### ISSUE TITLE
is-odd or is-even

### ISSUE THREAD

**Issue by alexcroox** [cloudflare/durable-objects-rollup-esm#12]
Package.json dependency is `is-even` but index.mjs uses `is-odd`

**Comment by koeninger** [comment]
is-even requires is-odd, which is why the example works.  In any case, the intention is just to give an example of a dependency on a package, not for the dependency to be particularly useful.

**Comment by nwpr** [comment]
Even though this issue is quite old, I would still recommend removing these dependencies and imports. I know it’s just an example; however, I consider the use of such modules unnecessary and bad practice. There’s no need for Cloudflare to support the spread and usage of these modules.
