### ISSUE TITLE
wrangler dev Uncaught Error: No such module "crypto"

### ISSUE THREAD

**Issue by sepiariver** [cloudflare/durable-objects-rollup-esm#16]
First off, thank you for making these templates. Without them, I highly doubt I could make much progress with Cloudflare Workers

This is the first time using this template, for me. My `rollup.config.js` is below, along with `package.json`

- `wrangler --version # 1.19.11`
- `npm test` passes
- `npm run build` success
- `wrangler dev --env dev` gets me:

```
src/index.mjs → dist/index.mjs...
created dist/index.mjs in 2.2s
Error: Something went wrong with the request to Cloudflare...
Uncaught Error: No such module "crypto".
  at line 0
 [API code: 10021]
 ```
*Is `crypto` not available as a global in the Workers runtime in module mode?* 

Things I've tried:

- various rollup plugins, including `'rollup-plugin-node-globals'` and `'rollup-plugin-node-polyfills'`
- referencing `crypto` directly vs `import {} from crypto`
- `env.crypto`

What I haven't tried:

- `crypto-js` I'm sort of loath to add it as a dependency and switch my API calls if `crypto` is _supposed_ to be available. NOTE: I currently include it as a devDependency for Jest only. This setup works on another, traditional Workers script (non-module)

`rollup.config.js`

```js
import { terser } from 'rollup-plugin-terser'
// plugin-node-resolve and plugin-commonjs are required for a rollup bundled project
// to resolve dependencies from node_modules. See the documentation for these plugins
// for more details.
import { nodeResolve } from '@rollup/plugin-node-resolve'
import commonjs from '@rollup/plugin-commonjs'
import { string } from 'rollup-plugin-string'

export default {
  input: 'src/index.mjs',
  output: {
    exports: 'named',
    format: 'es',
    file: 'dist/index.mjs',
    sourcemap: true,
  },
  plugins: [
    commonjs(),
    nodeResolve({
      exportConditions: ['node', 'browser', 'worker'],
      browser: true,
    }),
    string({
      include: "**/*.html",
    }),
    terser(),
  ],
}
```

`package.json`

```json
{
  "private": true,
  "name": "workers-module-mode",
  "version": "1.0.0",
  "description": "Workers in module-mode",
  "module": "./dist/index.mjs",
  "scripts": {
    "build": "rollup -c",
    "test": "node_modules/.bin/jest",
    "format": "prettier --write '**/*.{js,css,json,md}'"
  },
  "author": "sepiariver <info@sepiariver.com>",
  "devDependencies": {
    "@rollup/plugin-commonjs": "^17.0.0",
    "@rollup/plugin-node-resolve": "^11.1.0",
    "crypto": "^1.0.1",
    "jest": "^27.5.1",
    "prettier": "^1.19.1",
    "rollup": "^2.36.1",
    "rollup-jest": "^1.1.3",
    "rollup-plugin-copy": "^3.3.0",
    "rollup-plugin-string": "^3.0.0",
    "rollup-plugin-terser": "^7.0.2"
  },
  "jest": {
    "moduleDirectories": [
      "node_modules",
      "src"
    ],
    "transform": {
      "\\.m?js$": "rollup-jest"
    }
  },
  "dependencies": {
    "cookie": "^0.4.2",
    "itty-router": "^2.5.2",
    "rfc4648": "^1.5.1",
    "toucan-js": "^2.5.0"
  }
}
```

**Comment by koeninger** [comment]
Workers crypto docs are at https://developers.cloudflare.com/workers/runtime-apis/web-crypto/
What methods are you trying to call on it?

**Comment by sepiariver** [comment]
Thanks for your time on this, @koeninger 
Indeed I was mis-using crypto, either trying to call a method that doesn't exist in the Workers implementation, or trying to import it as a module.
To better align my dev environment with the Workers runtime, I'm switching to miniflare, which will hopefully help me avoid some of the pitfalls I've run into (of my own doing)
Closing...
